# .do/app.yaml - DigitalOcean App Platform Specification
name: storylofts-backend
region: nyc

services:
  - name: storylofts-backend
    source_dir: /
    github:
      repo: nsr-compute/storylofts-backend
      branch: main
    run_command: npm start
    build_command: node scripts/build-for-production.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: API_BASE_URL
        value: ${APP_URL}
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: AUTH0_DOMAIN
        value: ${AUTH0_DOMAIN}
      - key: AUTH0_AUDIENCE
        value: ${AUTH0_AUDIENCE}
      - key: B2_APPLICATION_KEY_ID
        value: ${B2_APPLICATION_KEY_ID}
      - key: B2_APPLICATION_KEY
        value: ${B2_APPLICATION_KEY}
      - key: B2_BUCKET_ID
        value: ${B2_BUCKET_ID}
      - key: B2_BUCKET_NAME
        value: ${B2_BUCKET_NAME}
      - key: MAX_FILE_SIZE
        value: "5368709120"
      - key: ALLOWED_VIDEO_FORMATS
        value: "mp4,mov,avi,mkv,webm"
      - key: ALLOWED_IMAGE_FORMATS
        value: "jpg,jpeg,png,webp"
      - key: USE_GOOGLE_SECRET_MANAGER
        value: "false"
    
    # Custom domains
    domains:
      - domain: api.storylofts.com
        type: PRIMARY
        wildcard: false
        certificate_type: LETS_ENCRYPT
    
    # Health check configuration
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # HTTP configuration
    http_port: 8080
